### ISSUE TITLE
metadata-generation-failed

### ISSUE THREAD

**Issue by tjw2469** [daswer123/xtts-finetune-webui#15]
since the console shut off by itself, so I recorded it and here is the screen shot:
![屏幕截图 2024-05-14 002424](https://github.com/daswer123/xtts-finetune-webui/assets/115522165/12856815-329c-4751-8b5b-b0cc662af75b)
Any solution?

**Comment by tjw2469** [comment]
found the solution:
https://github.com/daswer123/xtts-webui/issues/70

**Comment by SuperFurias** [comment]
> found the solution: [daswer123/xtts-webui#70](https://github.com/daswer123/xtts-webui/issues/70)
> 
> update: Even though with the method from the link above I managed to lunch finetune webui successfully, but it gives me error when I attempt to finetune a model
> 
> Traceback (most recent call last): File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\xtts_demo.py", line 246, in preprocess_dataset train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, whisper_model = whisper_model, target_language=language, out_path=out_path, gradio_progress=progress) File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\utils\formatter.py", line 131, in format_audio_list segments = list(segments) File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 1111, in restore_speech_timestamps for segment in segments: File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 508, in generate_segments encoder_output = self.encode(segment) File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 767, in encode return self.model.encode(features, to_cpu=to_cpu) RuntimeError: Library cublas64_12.dll is not found or cannot be loaded
> 
> What do I do?

and yes, now i have this same problem here

**Comment by SuperFurias** [comment]
> found the solution: [daswer123/xtts-webui#70](https://github.com/daswer123/xtts-webui/issues/70)
> 
> update: Even though with the method from the link above I managed to lunch finetune webui successfully, but it gives me error when I attempt to finetune a model
> 
> Traceback (most recent call last): File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\xtts_demo.py", line 246, in preprocess_dataset train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, whisper_model = whisper_model, target_language=language, out_path=out_path, gradio_progress=progress) File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\utils\formatter.py", line 131, in format_audio_list segments = list(segments) File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 1111, in restore_speech_timestamps for segment in segments: File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 508, in generate_segments encoder_output = self.encode(segment) File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 767, in encode return self.model.encode(features, to_cpu=to_cpu) RuntimeError: Library cublas64_12.dll is not found or cannot be loaded
> 
> What do I do?

fixed this issue too.
go inside folder xtts-finetune-webui\venv\Lib\site-packages\torch\lib
find files cublas64_11.dll and cublasLt64_11.dll
copy them inside same folder
rename them as cublas64_12.dll and cublasLt64_12.dll
problem fixed

**Comment by tjw2469** [comment]
> > The following is the error code I got:
> > Collecting jamo Using cached jamo-0.4.0.tar.gz (7.3 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> > × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [6 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\Users\Kai\AppData\Local\Temp\pip-install-al5q33xn\jamo_ff59e11714f544ec963a3d086b856b82\setup.py", line 11, in long_description = f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 703: illegal multibyte sequence [end of output]
> > note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> > × Encountered error while generating package metadata. ╰─> See above for output.
> > note: This is an issue with the package mentioned above, not pip. hint: See above for details.
> > Any solution?
> 
> just like the normal xtts-webui, the finetune webui one has the same problem too. i don't know why. this fixed the problem for me: run the install.bat file wait for everything to be installed see error close the cmd open a new cmd inside the folder type "call venv\Scripts\activate" type "pip install tts" wait for everything to be installed, close cmd then run again the install.bat file no more setup.py errors. don't ask me why, because i don't know

Thank you, it works!
