### ISSUE TITLE
Error during "Step 2 - run the training"

### ISSUE THREAD

**Issue by oMauOficial** [daswer123/xtts-finetune-webui#17]
Traceback (most recent call last):
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\MR\Finetune\xtts-finetune-webui\xtts_demo.py", line 339, in train_model
    os.remove(run_dir)
PermissionError: [WinError 5] Acesso negado: 'C:\\MR\\Finetune\\xtts-finetune-webui\\finetune_models\\run'
Traceback (most recent call last):
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\MR\Finetune\xtts-finetune-webui\xtts_demo.py", line 339, in train_model
    os.remove(run_dir)
PermissionError: [WinError 5] Acesso negado: 'C:\\MR\\Finetune\\xtts-finetune-webui\\finetune_models\\run'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\MR\Finetune\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by oMauOficial** [comment]
I managed to solve it simply by deleting the run folder (C:\xtts-finetune-webui\finetune_models\run) '-'

**Comment by kohai203** [comment]
> I managed to solve it simply by deleting the run folder (C:\xtts-finetune-webui\finetune_models\run) '-'

Thanks ! It helped me but right after this i'm getting :

" PermissionError: [WinError 32] couldn't access... 
/xtts-finetune-webui/finetune_models/run/training/GPT_XTTS_FT-May-19-2024_10+30AM-6cb8066\\trainer_0_log.txt' "

Can someone help ?

**Comment by oMauOficial** [comment]
@kohai203 If you are trying to train a second voice for example, try deleting the previous voice files generated in the "wavs" folder (C:\Finetune\xtts-finetune-webui\finetune_models\dataset\wavs").
Leave only the files that you are going to train at the moment, delete the "run" folder completely and try again, it worked for me =)

**Comment by PrometheusDante** [comment]
I'm getting this error as well:
 

> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:/VER_13/_AI/xtts-finetune-webui/finetune_models/run/training/GPT_XTTS_FT-May-22-2024_02+25AM-56af2c8\\trainer_0_log.txt'

And I've tried deleting the `run` folder as well as deleting everything inside `finetune_models` to restart the process, but to no avail.

**Comment by anastalaz** [comment]
I have the same problem. Anybody found a solution?

**Comment by Tenidus** [comment]
I ran into this exact issue so I restested using a previously trained model using it's reference audio and it worked which made me realize my new reference audio for the new voice must be bad.  I recreated the new reference files and tried learning the new model and it worked.  One thing I know I did with the new voices original reference was in Audacity I saved it as 4800mhz vs 4400mhz which could or could not be the culprit but that was the only variation I did.
So double check your reference audio being used for training is good.

**Comment by PrometheusDante** [comment]
It did actually work with a different audio file altogether. The first one was just as good, but for some reason the evaluation that happens in the beginning returned 0 usable parts, so it ran into the error because of that presumably.
The file I used now, which worked without issues using the default settings through the board, had the following specifications:

> stereo
> 48k
> 32bit
> .wav
> length: 2:00 min

What I noticed was that the step where it filters out invalid eval samples resulted in just 1 remaining, which would explain the mediocre result at the end. 
So maybe a way to tweak the threshold for permitting audio to be considered valid would solve the problem.

**Comment by PrometheusDante** [comment]
Alright, I've tested some more settings and approaches and I'm pretty sure this error is simply the result of the evaluation of the input audio amounting to 0 useable samples. I don't know what the criteria are, but the evaluation is very strictly sorting out your inputs. 
Would be nice to get feedback on why a sample didn't qualify to edit them better in preprocessing.
For now, I've managed to train models by following the advice and shared observations in this post:
https://www.reddit.com/r/Oobabooga/comments/1c09ank/so_you_want_to_finetune_an_xtts_model_let_me_help/
Quintessentially summarized as:
Using **multiple** audio inputs with 44.1khz, 16bit, mono, single sentences that do not exceed the maximum input audio size (default 11s) and using about 50-500 such files depending on the complexity of your target voice, wheres specific accents and dialects benefit from a larger dataset and more epochs.

I'm currently running a training where I input very clear and noiseless audio (video game voice acting). Exported in 78 small files, with only 22 making it through the eval step. So keep in mind that you might make a few hundred samples to have the majority of them revoked from the get-go for reasons undisclosed.

**Comment by biollas** [comment]
> Alright, I've tested some more settings and approaches and I'm pretty sure this error is simply the result of the evaluation of the input audio amounting to 0 useable samples. I don't know what the criteria are, but the evaluation is very strictly sorting out your inputs. Would be nice to get feedback on why a sample didn't qualify to edit them better in preprocessing. For now, I've managed to train models by following the advice and shared observations in this post: https://www.reddit.com/r/Oobabooga/comments/1c09ank/so_you_want_to_finetune_an_xtts_model_let_me_help/ Quintessentially summarized as: Using **multiple** audio inputs with 44.1khz, 16bit, mono, single sentences that do not exceed the maximum input audio size (default 11s) and using about 50-500 such files depending on the complexity of your target voice, wheres specific accents and dialects benefit from a larger dataset and more epochs.
> 
> I'm currently running a training where I input very clear and noiseless audio (video game voice acting). Exported in 78 small files, with only 22 making it through the eval step. So keep in mind that you might make a few hundred samples to have the majority of them revoked from the get-go for reasons undisclosed.

Yeah this same problem seems to be destroying everything I try to do.
