### ISSUE TITLE
Error on Training: get_git_branch

### ISSUE THREAD

**Issue by shu-toz** [daswer123/xtts-finetune-webui#22]
Hey All,

My Config:
3080 Laptop
CUDA 11.8
NVIDIA Driver 552
Windows 11

I tried a lot of different things, fresh install, fresh clone, no dice...
Any ideas??

Getting an error when pressing the training button:

 tts --model_name tts_models/multilingual/multi-dataset/xtts_v2 --text "Hello World, This is a voice clone speaking." --speaker_wav /workspace/dataset/*.wav --language_idx en --use_cuda true>> DVAE weights restored from: C:\xtts-finetune-webui\base_models\v2.0.2\dvae.pth
 | > Found 17 files in C:\xtts-finetune-webui\finetune_models\dataset
Traceback (most recent call last):
  File "C:\xtts-finetune-webui\xtts_demo.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\xtts-finetune-webui\utils\gpt_train.py", line 184, in train_gpt
    trainer = Trainer(
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\trainer.py", line 400, in __init__
    config, new_fields = self.init_training(args, coqpit_overrides, config)
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\trainer.py", line 752, in init_training
    new_fields["github_branch"] = get_git_branch()
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\generic_utils.py", line 44, in get_git_branch
    current = next(line for line in out.split("\n") if line.startswith("*"))
StopIteration
Traceback (most recent call last):
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\blocks.py", line 1369, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\blocks.py", line 1343, in validate_outputs
    raise ValueError(
ValueError: An event handler (train_model) didn't receive enough output values (needed: 6, received: 5).
Wanted outputs:
    [label, textbox, textbox, textbox, textbox, textbox]
Received outputs:
    ["The training was interrupted due an error !! Please check the console to check the full error message!
 Error summary: Traceback (most recent call last):
  File "C:\xtts-finetune-webui\xtts_demo.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\xtts-finetune-webui\utils\gpt_train.py", line 184, in train_gpt
    trainer = Trainer(
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\trainer.py", line 400, in __init__
    config, new_fields = self.init_training(args, coqpit_overrides, config)
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\trainer.py", line 752, in init_training
    new_fields["github_branch"] = get_git_branch()
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\generic_utils.py", line 44, in get_git_branch
    current = next(line for line in out.split("\n") if line.startswith("*"))
StopIteration
", "", "", "", ""]
Traceback (most recent call last):
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\blocks.py", line 1369, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\blocks.py", line 1343, in validate_outputs
    raise ValueError(
ValueError: An event handler (train_model) didn't receive enough output values (needed: 6, received: 5).
Wanted outputs:
    [label, textbox, textbox, textbox, textbox, textbox]
Received outputs:
    ["The training was interrupted due an error !! Please check the console to check the full error message!
 Error summary: Traceback (most recent call last):
  File "C:\xtts-finetune-webui\xtts_demo.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\xtts-finetune-webui\utils\gpt_train.py", line 184, in train_gpt
    trainer = Trainer(
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\trainer.py", line 400, in __init__
    config, new_fields = self.init_training(args, coqpit_overrides, config)
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\trainer.py", line 752, in init_training
    new_fields["github_branch"] = get_git_branch()
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\trainer\generic_utils.py", line 44, in get_git_branch
    current = next(line for line in out.split("\n") if line.startswith("*"))
StopIteration
", "", "", "", ""]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\xtts-finetune-webui\.venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by shu-toz** [comment]
Deleted the downloaded models and did everything from scratch, It seemed to have been using the existing XTTS model, which was causing issues.
