### ISSUE TITLE
Error when trying to create a dataset.

### ISSUE THREAD

**Issue by Mike-Schvedov** [daswer123/xtts-finetune-webui#24]
After adding a 5 minute wav / mp3 file and clicking on Step 1 - Create Dataset. I get this error:

The processing was interrupted due an error !! Please check the console to verify the full error message! Error summary: Traceback (most recent call last): File "D:\BackUpDrive\TextToSpeechAI\xtts-finetune-webui\xtts_demo.py", line 246, in preprocess_dataset train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, whisper_model = whisper_model, target_language=language, out_path=out_path, gradio_progress=progress) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "D:\BackUpDrive\TextToSpeechAI\xtts-finetune-webui\utils\formatter.py", line 80, in format_audio_list asr_model = WhisperModel(whisper_model, device=device, compute_type="float16") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BackUpDrive\TextToSpeechAI\xtts-finetune-webui\venv\Lib\site-packages\faster_whisper\transcribe.py", line 133, in __init__ self.model = ctranslate2.models.Whisper( ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

**Comment by Arctomachine** [comment]
I get this error on my gtx 960. Isnt any relatively modern card supposed to be fp16? And only high end cards fp32.
This card works in stable diffusion, where majority of models are fp16

**Comment by cryptotester** [comment]
I get the same error, I have a GPU GeForce GTX 1080 Ti, it works for stable diffusion. I get this error in Linux:

```
Traceback (most recent call last):
  File "/data/voice/xtts-finetune-webui/xtts_demo.py", line 267, in preprocess_dataset
    asr_model = WhisperModel(whisper_model, device=device, compute_type=compute_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/envs/xtts-finetune-webui/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 144, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
```

I think a possible solution would be to use float8, but how do we do that?

**Comment by Valkin22** [comment]
Had the same issue, but fixed it through the following:

1. Open the xtts_demo python file using an IDE

2. change:
 # Detect compute type 
                        if torch.cuda.is_available():
                            compute_type = "float16"
                        else:
                            compute_type = "float32"
     to:
 # Detect compute type 
                        if torch.cuda.is_available():
                            compute_type = "int8"
                        else:
                            compute_type = "float32"
                            
3. save

I tried float32 but ran into issues with training. I also had to lower my worker count to 4 because of memory issues with a 1080.
