### ISSUE TITLE
Multi-GPU

### ISSUE THREAD

**Issue by saintbrodie** [daswer123/xtts-finetune-webui#28]
Tried training a voice for the first time on a dual GPU system. Went to run training and got this error:

```
Traceback (most recent call last):                                                                                                           | 0.00/7.75M [00:00<?, ?iB/s]
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\xtts_demo.py", line 370, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\utils\gpt_train.py", line 184, in train_gpt
    trainer = Trainer(
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\trainer\trainer.py", line 435, in __init__
    self.use_cuda, self.num_gpus = self.setup_training_environment(args=args, config=config, gpu=gpu)
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\trainer\trainer.py", line 764, in setup_training_environment
    use_cuda, num_gpus = setup_torch_training_env(
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\trainer\trainer_utils.py", line 100, in setup_torch_training_env
    raise RuntimeError(
RuntimeError:  [!] 2 active GPUs. Define the target GPU by `CUDA_VISIBLE_DEVICES`. For multi-gpu training use `TTS/bin/distribute.py`.
Traceback (most recent call last):
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1397, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1371, in validate_outputs
    raise ValueError(
ValueError: An event handler (train_model) didn't receive enough output values (needed: 6, received: 5).
Wanted outputs:
    [label, textbox, textbox, textbox, textbox, textbox]
Received outputs:
    ["The training was interrupted due an error !! Please check the console to check the full error message!
 Error summary: Traceback (most recent call last):
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\xtts_demo.py", line 370, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\utils\gpt_train.py", line 184, in train_gpt
    trainer = Trainer(
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\trainer\trainer.py", line 435, in __init__
    self.use_cuda, self.num_gpus = self.setup_training_environment(args=args, config=config, gpu=gpu)
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\trainer\trainer.py", line 764, in setup_training_environment
    use_cuda, num_gpus = setup_torch_training_env(
  File "E:\Stable_Diffusion\xTTS\xtts-finetune-webui\venv\lib\site-packages\trainer\trainer_utils.py", line 100, in setup_torch_training_env
    raise RuntimeError(
RuntimeError:  [!] 2 active GPUs. Define the target GPU by `CUDA_VISIBLE_DEVICES`. For multi-gpu training use `TTS/bin/distribute.py`.
", "", "", "", ""]
```

I added  `CUDA_VISIBLE_DEVICES=0` to the top of xtts_demo.py and now its saying: 
`PermissionError: [WinError 5] Access is denied: 'E:\\Stable_Diffusion\\xTTS\\xtts-finetune-webui\\finetune_models\\run'`

**Comment by TheMaxik** [comment]
The training did start but it crashed. So you need to delete the "run" and "ready" folders in your finetune_models location.
AFAIK you cannot re train a model. This is what causing this error.

Btw if its still crashes after that with the Active GPU error. Then try to add CUDA_VISIBLE_DEVICES=0 as a env variable.

**Comment by saintbrodie** [comment]
That worked. I didn't know how to add an env variable. I put `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"` before importing torch and now it's training.

**Comment by merecesarchviz** [comment]
> That worked. I didn't know how to add an env variable. I put `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"` before importing torch and now it's training.

I have the same problem here!! i try to add an env variable dont work! where is to add the os.environ["CUDA_VISIBLE_DEVICES"] = "-1" in what file and in what position?
