### ISSUE TITLE
ASGI Exception Application

### ISSUE THREAD

**Issue by az1fr3** [daswer123/xtts-finetune-webui#53]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\fastapi\dependencies\utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\fastapi\dependencies\utils.py", line 810, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\fastapi\_compat.py", line 283, in get_model_fields
    return [
           ^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\fastapi\_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\fastapi\_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
                                           ^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\type_adapter.py", line 266, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\type_adapter.py", line 286, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\type_adapter.py", line 104, in _get_schema
    schema = gen.generate_schema(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2025, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
                            ^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2085, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\xtts-finetune-webui\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

**Comment by dotnetprofessional** [comment]
+1 on this

**Comment by rgsearcy** [comment]
I downgraded to gradio 4.08. I still get the error (a number of time for each audio file I use for training actually, but it is no longer a breaking issue. The issue also goes away if you upgrade to a gradio version >4.29.0, but this requires CUDA 12, which causes other issues.

**Comment by az1fr3** [comment]
@rgsearcy Thks! Works like a charm now!

**Comment by IVIaV** [comment]
Works for me, thx :D

**Comment by basketball-player** [comment]
> based on: [gradio-app/gradio#9278](https://github.com/gradio-app/gradio/issues/9278) I did the following commands:
> 
> * `pip install --upgrade pydantic==2.8.0`
> * `pip install --upgrade fastapi==0.112.4`
> * if you receive this error: `Library cublas64_12.dll is not found or cannot be loaded` you may need to go a pip upgrade for gradio to make sure you now have the proper dll for pydantic/fastapi.
> 
> This seems to have fixed the issue for me, for now.

Works, thank u <3

**Comment by coffeecodeconverter** [comment]
the specific fork that worked for me was this:
https://github.com/KataevEvgeniy/xtts-finetune-webui

these failed
https://github.com/aitrepreneur/xtts-finetune-webui
https://github.com/daswer123/xtts-webui?tab=readme-ov-file

the differences were the "requirements.txt" - heres the list from "KataevEvgeniy"'s fork that worked for me

faster_whisper==1.0.2
gradio==4.13.0
spacy==3.7.4
coqui-tts[languages] == 0.24.1

cutlet
fugashi[unidic-lite]
then also, as others have mentioned, also had to amend config.py under
xtts-webui\venv\Lib\site-packages\pydantic_internal\config.py

and change
arbitrary_types_allowed=False

to
arbitrary_types_allowed=True

NOT to be confused with the config.py found here:
xtts-webui\venv\Lib\site-packages\pydantic\config.py

despite having the same parameter "arbitrary_types_allowed"

reload your XTTS Server after making any changes.
should hopefully work.
