### ISSUE TITLE
Metadata train Empty 

### ISSUE THREAD

**Issue by az1fr3** [daswer123/xtts-finetune-webui#54]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
Existing language matches target language
Existing training metadata found and loaded.
Existing evaluation metadata found and loaded.
Dataset Processed!
Traceback (most recent call last):
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\xtts_demo.py", line 380, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\utils\gpt_train.py", line 177, in train_gpt
    train_samples, eval_samples = load_tts_samples(
                                  ^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\TTS\tts\datasets\__init__.py", line 123, in load_tts_samples
    meta_data_train = formatter(root_path, meta_file_train, ignored_speakers=ignored_speakers)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\TTS\tts\datasets\formatters.py", line 74, in coqui
    assert all(x in metadata[0] for x in ["audio_file", "text"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\TTS\tts\datasets\formatters.py", line 74, in <genexpr>
    assert all(x in metadata[0] for x in ["audio_file", "text"])
                    ~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\gradio\blocks.py", line 1397, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\gradio\blocks.py", line 1371, in validate_outputs
    raise ValueError(
ValueError: An event handler (train_model) didn't receive enough output values (needed: 6, received: 5).
Wanted outputs:
    [label, textbox, textbox, textbox, textbox, textbox]
Received outputs:
    ["The training was interrupted due an error !! Please check the console to check the full error message!
 Error summary: Traceback (most recent call last):
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\xtts_demo.py", line 380, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)


   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\utils\gpt_train.py", line 177, in train_gpt
    train_samples, eval_samples = load_tts_samples(
                                  ^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\TTS\tts\datasets\__init__.py", line 123, in load_tts_samples
    meta_data_train = formatter(root_path, meta_file_train, ignored_speakers=ignored_speakers)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\TTS\tts\datasets\formatters.py", line 74, in coqui
    assert all(x in metadata[0] for x in ["audio_file", "text"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\OVoice\FineTune Original\xtts-finetune-webui\venv\Lib\site-packages\TTS\tts\datasets\formatters.py", line 74, in <genexpr>
    assert all(x in metadata[0] for x in ["audio_file", "text"])
                    ~~~~~~~~^^^
IndexError: list index out of range
", "", "", "", ""]

**Comment by IVIaV** [comment]
Did you found a solution?
