### ISSUE TITLE
Cannot Create Data Set

### ISSUE THREAD

**Issue by Vorelisk** [daswer123/xtts-finetune-webui#56]
When I load an audio file and try to create a dataset, I get an instant error/crash and the following output:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\fastapi\dependencies\utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\fastapi\dependencies\utils.py", line 813, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\fastapi\_compat.py", line 283, in get_model_fields
    return [
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\fastapi\_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\fastapi\_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "B:\XTTS\xtts-finetune-webui\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

I tried my best to find any information on the issue, but I could not find anyone discussing this anywhere. Hopefully this is just a newbie issue.

**Comment by IVIaV** [comment]
Try maybe this :)
https://github.com/daswer123/xtts-finetune-webui/issues/53

**Comment by maxsubs** [comment]
I had this same error, something is wrong with install.bat commands and requirements, versions conflicts
I could fix this error, but still can't create dataset, I have no knowledge but this fixed this error:

on windows, open cmd

navigate to the xtts fine tune folder:
cd F:\Soft\AI\xtts-finetune-webui-main

python -m venv venv

pip uninstall gradio
pip install gradio==4.12.0

pip install spacy==3.5.0 weasel==0.3.2

then start.bat and it should process dataset without this error
