### ISSUE TITLE
cublas64_12.dll is not found or cannot be loaded 

### ISSUE THREAD

**Issue by ChairmanMeow999** [daswer123/xtts-finetune-webui#66]
Thought i had this fixed but i guess not. I was getting the same error outlined in this post 
[https://github.com/daswer123/xtts-finetune-webui/issues/56](url)

I followed the solution that was given here and i thought it fixed my issue but in reality it just got me to the point where it was downloading the model and fooled me into thinking it was actually working. I was doing some looking around in the issues section and found someone referencing it here 
[https://github.com/daswer123/xtts-finetune-webui/issues/53#issuecomment-2333939074](url)

He says at the end of the post "if you receive this error: Library cublas64_12.dll is not found or cannot be loaded you may need to go a pip upgrade for gradio to make sure you now have the proper dll for pydantic/fastapi."

And well that's the exact error message im getting and i thought i followed everything he said but im still getting the issue... I've tried deleting everything ai related included cuda and python and reinstalling it and im still getting the same error i've even gone through everything in the post he referenced in his comment
[https://github.com/gradio-app/gradio/issues/9278](url)

I've tried everything and still no dice... if anyone has any ideas that would be great. Here is my error message.

`The data processing was interrupted due an error !! Please check the console to verify the full error message! Error summary: Traceback (most recent call last): File "D:\stable3\TTS\xtts-finetune-webui\xtts_demo.py", line 246, in preprocess_dataset train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, whisper_model = whisper_model, target_language=language, out_path=out_path, gradio_progress=progress) File "D:\stable3\TTS\xtts-finetune-webui\utils\formatter.py", line 131, in format_audio_list segments = list(segments) File "D:\stable3\TTS\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 1111, in restore_speech_timestamps for segment in segments: File "D:\stable3\TTS\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 508, in generate_segments encoder_output = self.encode(segment) File "D:\stable3\TTS\xtts-finetune-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 767, in encode return self.model.encode(features, to_cpu=to_cpu) RuntimeError: Library cublas64_12.dll is not found or cannot be loaded `

**Comment by epicstar7** [comment]
From https://github.com/daswer123/xtts-finetune-webui/issues/15#issuecomment-2110778923

> go inside folder xtts-finetune-webui\venv\Lib\site-packages\torch\lib
> find files cublas64_11.dll and cublasLt64_11.dll
> copy them inside same folder
> rename them as cublas64_12.dll and cublasLt64_12.dll
> so you will have 4 files
> cublas64_11.dll
> cublas64_12.dll
> cublasLt64_11.dll
> cublasLt64_12.dll
> problem fixed

**Comment by ChairmanMeow999** [comment]
> From [#15 (comment)](https://github.com/daswer123/xtts-finetune-webui/issues/15#issuecomment-2110821552)
> 
> > go inside folder xtts-finetune-webui\venv\Lib\site-packages\torch\lib
> > find files cublas64_11.dll and cublasLt64_11.dll
> > copy them inside same folder
> > rename them as cublas64_12.dll and cublasLt64_12.dll
> > so you will have 4 files
> > cublas64_11.dll
> > cublas64_12.dll
> > cublasLt64_11.dll
> > cublasLt64_12.dll
> > problem fixed

Ok that definitely helped i was able to actually click the create dataset button and it even got to 100% but then it gave me an blank error with nothing appearing in the console. although it did output files into "finetune_models" anyone know why that might be?

**Comment by ChairmanMeow999** [comment]
> > From [#15 (comment)](https://github.com/daswer123/xtts-finetune-webui/issues/15#issuecomment-2110821552)
> > > go inside folder xtts-finetune-webui\venv\Lib\site-packages\torch\lib
> > > find files cublas64_11.dll and cublasLt64_11.dll
> > > copy them inside same folder
> > > rename them as cublas64_12.dll and cublasLt64_12.dll
> > > so you will have 4 files
> > > cublas64_11.dll
> > > cublas64_12.dll
> > > cublasLt64_11.dll
> > > cublasLt64_12.dll
> > > problem fixed
> 
> Ok that definitely helped i was able to actually click the create dataset button and it even got to 100% but then it gave me an blank error with nothing appearing in the console. although it did output files into "finetune_models" anyone know why that might be?

Alright it's officially fixed!!! I reinstalled the webui completely then to fix the pydantic error i did 
pip install --upgrade pydantic==2.8.0
pip install --upgrade fastapi==0.112.4

Then i was left with one more error the cublas64_12.dll is not found or cannot be loaded so i then did what epicstar7 outlined to fix that error and now i can actually create a dataset and have it fully complete and get the "Dataset Processed!" prompt. YAYYYYYYYY thanks for the help epicstar7
