### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by spike4379** [daswer123/xtts-finetune-webui#7]
Hey dude, I just started getting this error today when running the finetuning after I made a dataset, then i tried to install a brand new fresh install and during installation this is the error its giving me
[log.txt](https://github.com/daswer123/xtts-finetune-webui/files/13971078/log.txt)

I attached a longer version of as much as the window would hold to copy. Common theme seems to be the asgi? Any suggestions on what I should do?

My other python installs for things like oobabooga and SD are working alright and without issue.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\responses.py", line 261, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\responses.py", line 257, in wrap
    await func()
  File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\responses.py", line 234, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 534, in receive
    await self.message_event.wait()
  File "C:\Python311\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 231ab30ae90

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\responses.py", line 254, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\responses.py", line 257, in wrap
    |     await func()
    |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\starlette\responses.py", line 246, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "F:\ChatGPT\xtts-finetune-webui\venv\Lib\site-packages\gradio\routes.py", line 602, in sse_stream
    |     raise HTTPException(
    | fastapi.exceptions.HTTPException: 404: Session not found.

**Comment by spike4379** [comment]
Resolved after a forced restart of the system, sorry to waste your time. I also keep getting the error unless I also close the gradio page. interesting

**Comment by az1fr3** [comment]
@spike4379  How you solve this? Im getting the same error.
