### ISSUE TITLE
[Errno 2] No such file or directory: 'finetune_models\\dataset\\metadata_train.csv'

### ISSUE THREAD

**Issue by bews** [daswer123/xtts-finetune-webui#85]
Tried running the latest version and it doesn't work: after I select an audio and click "Step 1: Create dataset" it loads GPU fo some time and then gives this error:

`To create a public link, set `share=True` in `launch()`.
Existing language matches target language
Traceback (most recent call last):
  File "I:\TTS\xtts-finetune-webui\xtts_demo.py", line 314, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(audio_files, asr_model=asr_model, target_language=language, out_path=out_path, gradio_progress=progress)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\TTS\xtts-finetune-webui\utils\formatter.py", line 184, in format_audio_list
    new_data_df = pandas.read_csv(train_metadata_path, sep="|")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\TTS\xtts-finetune-webui\venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\TTS\xtts-finetune-webui\venv\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\TTS\xtts-finetune-webui\venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\TTS\xtts-finetune-webui\venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "I:\TTS\xtts-finetune-webui\venv\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'I:\\TTS\\xtts-finetune-webui\\finetune_models\\dataset\\metadata_train.csv'`

**Comment by bews** [comment]
Downgrading to faster_whisper==1.0.2 solves this problem.

**Comment by IbrahimOzmen** [comment]
bro can i ask u something? do u know how can i use this model on my local device or pc? ı need to implement this model to my mobile application do u know how or do u have any documentation?

**Comment by TinyForge** [comment]
I'm running into the exact same issue as above. Downgrading my faster_whisper to 1.0.2 has not solved the problem.

**Comment by bews** [comment]
> I'm running into the exact same issue as above. Downgrading my faster_whisper to 1.0.2 has not solved the problem.

Welp what I did was:
1. Downgraded to Dec 30, 2023 commit (it started crashing instead)
2. Recreated the venv and did a manual clean install [pip install torch==2.1.1+cu118 torchaudio==2.1.1+cu118 --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt] with the requirements.txt from the lastest version (still were crashing)
3. Downgraded to faster_whisper==1.0.2 (the old version started working with this combo)
4. Updated to the latest commit - it started working too

**Comment by rock5917** [comment]
The reason for this error is the absence of required files in the folder:
xtts-finetune-webui\base_models\v2.0.2

Fix: Download the necessary files from the source:
https://huggingface.co/coqui/XTTS-v2/tree/v2.0.2
